//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MasakinEntities : DbContext
    {
        public DB_MasakinEntities()
            : base("name=DB_MasakinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblM_Menu> tblM_Menu { get; set; }
        public virtual DbSet<tblT_Catering> tblT_Catering { get; set; }
        public virtual DbSet<tblT_Transaction> tblT_Transaction { get; set; }
        public virtual DbSet<tblT_Transaction_Detail> tblT_Transaction_Detail { get; set; }
        public virtual DbSet<tblT_Payment> tblT_Payment { get; set; }
    }
}
