//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_MasterEntities : DbContext
    {
        public DB_MasterEntities()
            : base("name=DB_MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblM_Admin> tblM_Admin { get; set; }
        public virtual DbSet<tblM_Balance> tblM_Balance { get; set; }
        public virtual DbSet<tblM_Banner> tblM_Banner { get; set; }
        public virtual DbSet<tblM_Kabupaten> tblM_Kabupaten { get; set; }
        public virtual DbSet<tblM_Kecamatan> tblM_Kecamatan { get; set; }
        public virtual DbSet<tblM_Provinsi> tblM_Provinsi { get; set; }
        public virtual DbSet<tblT_Address> tblT_Address { get; set; }
        public virtual DbSet<tblT_Log_Admin> tblT_Log_Admin { get; set; }
        public virtual DbSet<tblT_User_Token> tblT_User_Token { get; set; }
        public virtual DbSet<tblM_User_DeviceID> tblM_User_DeviceID { get; set; }
        public virtual DbSet<tblM_Merchant_DeviceID> tblM_Merchant_DeviceID { get; set; }
        public virtual DbSet<tblT_Merchant_Delivery_Location> tblT_Merchant_Delivery_Location { get; set; }
        public virtual DbSet<tblM_User> tblM_User { get; set; }
    }
}
