//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Banner
    {
        public long BannerID { get; set; }
        public string Header { get; set; }
        public string Image { get; set; }
        public string ContentType { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    }
}
