//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Balance
    {
        public long BalanceID { get; set; }
        public long MerchantID { get; set; }
        public double Balance { get; set; }
        public System.DateTime LastTopup { get; set; }
        public System.DateTime LastUsed { get; set; }
    }
}
