//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_User
    {
        public long UserID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public string Gender { get; set; }
        public string DoB { get; set; }
        public Nullable<System.DateTime> DateJoin { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public Nullable<int> isVerified { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<int> isBanned { get; set; }
        public Nullable<int> SMSCount { get; set; }
        public string FBID { get; set; }
        public string ImageURL { get; set; }
        public string ThumbnailURL { get; set; }
        public Nullable<int> isMerchant { get; set; }
        public Nullable<double> Balance { get; set; }
        public string DeliveryLocation { get; set; }
        public string DeviceID { get; set; }
    }
}
