//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Merchant_DeviceID
    {
        public long MerchantID { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
