//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblM_Menu
    {
        public long MenuID { get; set; }
        public long MerchantID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public Nullable<double> Rate { get; set; }
        public int isActive { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ImageURL { get; set; }
        public string ThumbnailURL { get; set; }
    }
}
