//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Catering
    {
        public long CateringID { get; set; }
        public long LocalID { get; set; }
        public Nullable<long> MerchantID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Temporary { get; set; }
        public Nullable<int> Sold { get; set; }
        public Nullable<long> Day1MenuID { get; set; }
        public Nullable<long> Day2MenuID { get; set; }
        public Nullable<long> Day3MenuID { get; set; }
        public Nullable<long> Day4MenuID { get; set; }
        public Nullable<long> Day5MenuID { get; set; }
        public Nullable<System.DateTime> DateFirst { get; set; }
        public Nullable<System.DateTime> DateLast { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int isActive { get; set; }
        public int isRepeat { get; set; }
        public string DeliveryLocation { get; set; }
        public tblM_User Merchant { get; set; }
        public List<tblM_Menu> Menu { get; set; }
    }
}
