//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Merchant_Delivery_Location
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long ProvinsiID { get; set; }
        public long KabupatenID { get; set; }
        public int isActive { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
