//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Address
    {
        public long AddressID { get; set; }
        public long UserID { get; set; }
        public string AddressHeader { get; set; }
        public string AddressName { get; set; }
        public string Addressee { get; set; }
        public string Phone { get; set; }
        public long ProvinsiID { get; set; }
        public long KabupatenID { get; set; }
        public Nullable<int> ZIPCode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
