//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Transaction
    {
        public string TransactionID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> MerchantID { get; set; }
        public Nullable<long> CateringID { get; set; }
        public Nullable<System.DateTime> DateFirst { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> ShippingCost { get; set; }
        public Nullable<double> Total { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> isPaid { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public string StatusMessage { get; set; }
        public string Deliveree { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string HomeNumber { get; set; }
        public string Notes { get; set; }
        public string Voucher { get; set; }
        public string URL { get; set; }
        public Nullable<int> VoucherAmount { get; set; }
        public tblT_Catering Catering { get; set; }
        public List<tblM_Menu> Menu { get; set; }
    }
}
