//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masakin
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Payment
    {
        public string Ref { get; set; }
        public string TransactionID { get; set; }
        public string URL { get; set; }
        public string Trace { get; set; }
        public string Status { get; set; }
        public string StatusMessage { get; set; }
    }
}
